backend:
  name: git-gateway
  branch: main
site_url: https://gyacboxing.netlify.app
api_root: https://api.netlify.com/build_hooks/69fb76ba850783968733aca8
media_folder: "src/assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/_data/site.json"
        fields:
          - { label: "Hero Image URL", name: "hero_image", widget: "string" }
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "string" }
          - { label: "Goals Section Image URL", name: "goals_image", widget: "string" }
          - { label: "About Section Image URL", name: "about_image", widget: "string" }
          - { label: "Gallery Photo 1 URL", name: "gallery_photo_1", widget: "string" }
          - { label: "Gallery Photo 2 URL", name: "gallery_photo_2", widget: "string" }
          - { label: "Gallery Photo 3 URL", name: "gallery_photo_3", widget: "string" }
          - { label: "Gallery Photo 4 URL", name: "gallery_photo_4", widget: "string" }
          - { label: "Gallery Photo 5 URL", name: "gallery_photo_5", widget: "string" }